apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git17
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@git.17usoft.com:Serverless/test-serverless-js.git
